name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/apps-data/qbittorrent/config:/config
      - /data/media/Downloads/torrents:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /data/apps-data/jellyfin/config:/config
      - /data/media/tvshows:/data/tvshows
      - /data/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped